name: foodex_app
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.4
  responsive_sizer: ^3.0.8
  supabase: ^0.3.6
  supabase_flutter: ^0.3.3
  bottom_navy_bar: ^6.0.0
  flutter_rating_bar: ^4.0.1
  lottie: ^1.4.1
  flutter_svg: ^2.0.5
  dio: ^5.1.2
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5


flutter_native_splash:
  image: assets/images/Logo.png
  color: "#ffffff"
  backgroundimage: assets/images/Pattern.png


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/
